/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BCollapse: typeof import('bootstrap-vue-next/components/BCollapse')['BCollapse']
    BDropdown: typeof import('bootstrap-vue-next/components/BDropdown')['BDropdown']
    BModal: typeof import('bootstrap-vue-next/components/BModal')['BModal']
    BNavbar: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue-next/components/BNavbar')['BNavbarToggle']
    BNavForm: typeof import('bootstrap-vue-next/components/BNav')['BNavForm']
    BufferSizeFilter: typeof import('./src/components/core/filters/BufferSizeFilter.vue')['default']
    ConfiguratorWidget: typeof import('./src/components/ConfiguratorWidget.vue')['default']
    DateFilter: typeof import('./src/components/core/filters/DateFilter.vue')['default']
    Error404: typeof import('./src/components/commons/Error404.vue')['default']
    Filters: typeof import('./src/components/core/Filters.vue')['default']
    HTMLBuilder: typeof import('./src/components/core/HTMLBuilder.vue')['default']
    Intro: typeof import('./src/components/core/Intro.vue')['default']
    LanguageSwitch: typeof import('./src/components/commons/LanguageSwitch.vue')['default']
    ListWidget: typeof import('./src/components/ListWidget.vue')['default']
    Loading: typeof import('./src/components/commons/Loading.vue')['default']
    Map: typeof import('./src/components/core/Map.vue')['default']
    MapListWidget: typeof import('./src/components/MapListWidget.vue')['default']
    Pagination: typeof import('./src/components/commons/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Share: typeof import('./src/components/core/Share.vue')['default']
    SortBy: typeof import('./src/components/commons/SortBy.vue')['default']
    SourceFilter: typeof import('./src/components/core/filters/SourceFilter.vue')['default']
    Taxon: typeof import('./src/components/core/Taxon.vue')['default']
    TaxonList: typeof import('./src/components/core/TaxonList.vue')['default']
    TaxonResearch: typeof import('./src/components/core/filters/TaxonResearch.vue')['default']
  }
  export interface ComponentCustomProperties {
    vBColorMode: typeof import('bootstrap-vue-next/directives/BColorMode')['vBColorMode']
    vBModal: typeof import('bootstrap-vue-next/directives/BModal')['vBModal']
  }
}
